#!/usr/bin/env python3

from textwrap import dedent

import click

from xf_capture.setup import setup_workflow
from xf_capture.runner import run_pipeline
from xf_capture.multiphylo import run_multiphylo


def _print_version(ctx: click.Context, param: click.Parameter, value: bool) -> None:
    if not value or ctx.resilient_parsing:
        return

    try:
        from importlib.metadata import version
    except ImportError:
        from importlib_metadata import version

    try:
        pkg_version = version("xf_capture")
    except Exception:
        pkg_version = "unknown"

    click.echo(f"v.{pkg_version}")
    ctx.exit()


class OrderedGroup(click.Group):
    """Lists subcommands in registration order instead of alphabetically."""

    def list_commands(self, ctx: click.Context) -> list:
        return list(self.commands)


@click.group(
    cls=OrderedGroup,
    name="xf_capture",
    context_settings={"help_option_names": ["-h", "--help"]},
    invoke_without_command=True,
    help=dedent(
        """
        This tool is a Snakemake-based workflow for processing paired-end sequencing
        data generated by Xf-TSCE experiments.
        """
    ),
    epilog=dedent(
        """
        \b
        Typical usage:

        \b
          xf_capture setup --dir xf_workflow
          xf_capture run -i fastq_files/ -o results/
          xf_capture multi-phylo -o results/ --samples-list samples.txt

        For help on a specific command:

        \b
          xf_capture <command> --help
        """
    ),
)
@click.option(
    "-v", "--version",
    is_flag=True,
    expose_value=False,
    is_eager=True,
    callback=_print_version,
    help="Show xf_capture version and exit",
)
@click.pass_context
def cli(ctx: click.Context) -> None:
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


# ----------------------------------------------------------------------------
# setup command
# ----------------------------------------------------------------------------
@cli.command(
    "setup",
    short_help="Prepare workflow resources (references, databases, configs)",
    help=dedent(
        """
        Prepare the XfCapture workflow environment.

        This command initializes the workflow directory, extracts reference sequences,
        downloads required databases (i.e. Kraken2), and stores user-specific configuration.
        """
    ),
)
@click.option(
    "--dir", "dir_",
    required=True,
    metavar="",
    help="Directory where the workflow environment will be created",
)
@click.option(
    "--k2-db",
    type=click.Choice(["8GB", "16GB", "FULL"]),
    default="8GB",
    metavar="",
    help="Kraken2 database size to download: 8GB, 16GB, or FULL (default: 8GB)",
)
def setup_cmd(dir_: str, k2_db: str) -> None:
    setup_workflow(dir_, k2_db=k2_db)


# ----------------------------------------------------------------------------
# run command
# ----------------------------------------------------------------------------
@cli.command(
    "run",
    context_settings={"ignore_unknown_options": True},
    short_help="Run the XfCapture Snakemake pipeline",
    help=dedent(
        """
        Execute the XfCapture pipeline on paired-end sequencing data.

        This command generates a configuration file and launches
        Snakemake using the packaged workflow.
        """
    ),
)
# Input / Output options
@click.option(
    "-i", "--input-dir", "input_dir",
    default=None,
    metavar="",
    help="Directory containing paired-end FASTQ files",
)
@click.option(
    "-o", "--output-dir", "output_dir",
    default=None,
    metavar="",
    help="Directory where results will be written",
)
# Workflow configuration
@click.option(
    "--workflow-dir",
    default=None,
    metavar="",
    help="Path to an existing workflow directory (optional)",
)
@click.option(
    "--kraken-db",
    default=None,
    metavar="",
    help="Path to a Kraken2 database (optional)",
)
# Resource allocation
@click.option(
    "--cores",
    type=int,
    default=16,
    metavar="",
    help="Total number of CPU cores to use (default: 16)",
)
@click.option(
    "--kraken-jobs",
    type=int,
    default=1,
    metavar="",
    help="Number of parallel Kraken2 jobs (default: 1)",
)
@click.option(
    "--alignment-jobs",
    type=int,
    default=4,
    metavar="",
    help="Number of parallel alignment jobs (default: 4)",
)
@click.option(
    "--iqtree-jobs",
    type=int,
    default=2,
    metavar="",
    help="Number of parallel IQ-TREE jobs (default: 2)",
)
@click.option(
    "--iqtree-threads",
    type=int,
    default=8,
    metavar="",
    help="Number of threads per IQ-TREE job (default: 8)",
)
@click.option(
    "--kraken-threads",
    type=int,
    default=8,
    metavar="",
    help="Number of threads per Kraken2 job (default: 8)",
)
@click.option(
    "--no-auto",
    is_flag=True,
    default=False,
    help="Disable automatic continuation to phylogenetic analysis (requires confirmation)",
)
@click.option(
    "--k2-mapping-memory",
    is_flag=True,
    default=False,
    help="Enable Kraken2 memory mapping mode (avoids loading entire database into RAM, default: False)",
)
@click.argument("extra_args", nargs=-1, type=click.UNPROCESSED)
def run_cmd(
    input_dir: str,
    output_dir: str,
    workflow_dir: str,
    kraken_db: str,
    cores: int,
    kraken_jobs: int,
    alignment_jobs: int,
    iqtree_jobs: int,
    iqtree_threads: int,
    kraken_threads: int,
    no_auto: bool,
    k2_mapping_memory: bool,
    extra_args: tuple,
) -> None:
    missing = []
    if input_dir is None:
        missing.append("--input-dir")
    if output_dir is None:
        missing.append("--output-dir")

    if missing:
        raise click.UsageError(
            f"run requires the following arguments: {', '.join(missing)}"
        )

    run_pipeline(
        input_dir=input_dir,
        output_dir=output_dir,
        workflow_dir=workflow_dir,
        kraken_db=kraken_db,
        cores=cores,
        kraken_jobs=kraken_jobs,
        alignment_jobs=alignment_jobs,
        iqtree_jobs=iqtree_jobs,
        kraken_threads=kraken_threads,
        iqtree_threads=iqtree_threads,
        auto=not no_auto,
        k2_mapping_memory=k2_mapping_memory,
        extra_args=list(extra_args) if extra_args else None,
    )


# ----------------------------------------------------------------------------
# multi-phylo command
# ----------------------------------------------------------------------------
@cli.command(
    "multi-phylo",
    context_settings={"ignore_unknown_options": True},
    short_help="Build a joint phylogenetic tree from a selected subset of samples",
    help=dedent(
        """
        Build a single joint phylogenetic tree from a user-selected subset
        of samples that already completed Phase 1 in a prior `xf_capture run`.

        The tree is restricted to the genes reconstructed in ALL of the
        selected samples (intersection by gene identifier), aligned together
        with the reference genomes.
        """
    ),
)
@click.option(
    "-o", "--output-dir", "output_dir",
    required=True,
    metavar="",
    help="Output directory from a previous 'xf_capture run' (must contain run_config.yaml)",
)
@click.option(
    "--samples-list",
    required=True,
    metavar="",
    help="Text file with one sample name per line to include in the joint tree",
)
@click.option(
    "--workflow-dir",
    default=None,
    metavar="",
    help="Path to an existing workflow directory (optional)",
)
@click.option(
    "--cores",
    type=int,
    default=16,
    metavar="",
    help="Total number of CPU cores to use (default: 16)",
)
@click.option(
    "--iqtree-threads",
    type=int,
    default=8,
    metavar="",
    help="Number of threads for the joint IQ-TREE job (default: 8)",
)
@click.option(
    "--alignment-jobs",
    type=int,
    default=4,
    metavar="",
    help="Number of parallel alignment jobs (default: 4)",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Force rerunning the multi-phylo subgraph even if outputs already exist",
)
@click.argument("extra_args", nargs=-1, type=click.UNPROCESSED)
def multi_phylo_cmd(
    output_dir: str,
    samples_list: str,
    workflow_dir: str,
    cores: int,
    iqtree_threads: int,
    alignment_jobs: int,
    force: bool,
    extra_args: tuple,
) -> None:
    run_multiphylo(
        output_dir=output_dir,
        samples_list=samples_list,
        workflow_dir=workflow_dir,
        cores=cores,
        iqtree_threads=iqtree_threads,
        alignment_jobs=alignment_jobs,
        force=force,
        extra_args=list(extra_args) if extra_args else None,
    )


def main() -> None:
    cli()


if __name__ == "__main__":
    main()
